SELECT CAST(c AS DECIMAL(4,1)) * CAST(b AS DOUBLE) FROM t
----
SELECT CAST(c AS DECIMAL(4,1)) + CAST(b AS DOUBLE) FROM t
----
SELECT CAST(c AS DECIMAL(4,1)) - CAST(b AS DOUBLE) FROM t
----
SELECT CAST(c AS DECIMAL(10,2)) * c FROM t
----
SELECT CAST(b AS DECIMAL(10,0)) * c FROM t
----
SELECT a, SUM(CAST(c AS DECIMAL(4,1)) * CAST(b AS DOUBLE)) FROM t GROUP BY a
----
SELECT CAST(c AS DECIMAL(4,1)) = CAST(b AS DOUBLE) FROM t
----
SELECT CAST(c AS DECIMAL(4,1)) / CAST(b AS DOUBLE) FROM t
----
SELECT SIN(CAST(c AS DECIMAL(4,1))) FROM t
